kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: default
  image:
    name: tutum/hello-world
    tag: '818aa23b2cc05cc3998506faf24ecfbd2bf5ec17'
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress