kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: default
  image:
    name: ch0d0r/test
    tag: 'latest'
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress
