kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: default
  image:
    name: tutum/hello-world
    tag: '2fcce306b6b6b70991643a3eb610cc3e314eef79'
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress